### ISSUE TITLE
Randomness.

### ISSUE THREAD

**Issue by adam505hq** [SkArchon/harmony-social-game#2]
Currently I see this is used:

``` Solidity
  function generateRand() private view returns (bytes32 result) {
		bytes32 input;
		assembly {
			let memPtr := mload(0x40)
					if iszero(staticcall(not(0), 0xff, input, 32, memPtr, 32)) {
						invalid()
					}
					result := mload(memPtr)
			}
  	}
```

It was suggested to use Harmony specific solution here -> https://github.com/harmony-one/bounties/issues/47#issuecomment-854991917

Couple of questions:
1. Why wasn't VRF random number generator used?
2. Is current method secure ?
3. Could you briefly describe what is happening in this code? I see it's pretty low level.
4. Would it be difficult to switch to Harmony solution ?

**Comment by SkArchon** [comment]
So the randomness is based on the source in this https://github.com/harmony-one/harmony/issues/3719
(was linked in the bounty issue that you also attached)

With that in mind could you reclarify your questions.

**Comment by adam505hq** [comment]
Sorry about this I see that this is official way. I wasn't aware of this before.
